### ISSUE TITLE
Designate from Armok Vision

### ISSUE THREAD

**Issue by kazimuth** [JapaMala/armok-vision#13]
It would be totally rad if you could select areas and then designate them from Armok Vision. If we do designations, zones, and buildings, that's a large chunk of Fortress Mode playable from Unity, and it'll hopefully be reasonably straightforward to implement. Of course, it also opens the doors to loads and loads of bugs and complexities and issues; the biggest challenge would be avoiding accidentally violating DFs invariants.

**Comment by JapaMala** [comment]
Controlling DF from unity requires three things : defining the network
protocol for it, using protobufs, adding the functionality to the server
plugin, and finally doing the unity side of things.

**Comment by PeridexisErrant** [comment]
Using [Mifki's forthcoming protocol](http://www.bay12forums.com/smf/index.php?topic=145944) is probably the best way to approach this.  He's said an alpha version should be out soon, and that opens an interface for anything in the game!

**Comment by JapaMala** [comment]
That will work if it's open source, which it may not be, all things considered.

**Comment by PeridexisErrant** [comment]
[Here:](http://www.bay12forums.com/smf/index.php?topic=145944.msg5828447#msg5828447)

>>Will you be able to put this on android? It's super-awesome, to whatever use it gets put, but I'd love it on my tablet.

>iOS version alone is enough work for me for a long time (with all the ideas I have), and I'm an iOS developer, so **I personally won't be doing other platforms, but others hopefully will.**

The app (iOS client) may be closed-source, but the UI server almost certainly won't.

**Comment by JapaMala** [comment]
Added in ae3aba491c35469cc3d9548ce336fef11a2ee9ee
