### ISSUE TITLE
Enhancement idea: Only show discovered tiles

### ISSUE THREAD

**Issue by qrush** [JapaMala/armok-vision#22]
Just an idea here. I have a fortress I'm working on, but I don't want to spoil what's inside the layers of rock I haven't dug into yet. It would be nice if there was a "spoiler" mode that would show everything (enabled by default), and I could disable that to only show what I can see or have built thus far.

**Comment by JapaMala** [comment]
This is the generall idea, actually. I don't want to do spoilers at all, actually, but I have't enabled the feature yet.

Once I don't show unexplored tiles, I can also use that as a performance booster, which I need, so I should start working on that.

**Comment by JapaMala** [comment]
This is working now.

**Comment by qrush** [comment]
Nice!!!
