### ISSUE TITLE
Armok Vision not running in Ubuntu because of case sensitive names

### ISSUE THREAD

**Issue by ragundo** [JapaMala/armok-vision#26]
Platform: Ubuntu 64 bits.
Downloaded from github. Started, nothing happens, only a blank screen, no map showed nor blocks received from DF.
After checking the log file in 
/home/.config/unity3d/DefaultCompany/Armok Vision/Player.log
It was found that the problem was the asset WindMill.obj that needs to be renamed to Windmill.obj.

After renaming the asset. Armok Vision works ok

**Comment by JapaMala** [comment]
This actually raises another issue that it shouldn't break if a file isn't found. Just log an error.

**Comment by JapaMala** [comment]
Fixed in 14fda759b756a2334359258f0d432e80e8112f7b
