### ISSUE TITLE
Distribute a manifest.json, for PyLNP

### ISSUE THREAD

**Issue by PeridexisErrant** [JapaMala/armok-vision#32]
It would be great if a [manifest for PyLNP](https://bitbucket.org/Pidgeot/python-lnp/overview#rst-header-content-manifests) could be included, along with the other ReleaseFiles.  Here's what I'm using for Armok Vision:

    {
    "win_exe": "Armok Vision.exe",
    "tooltip": "A full 3D visualiser - shows off Dwarf Fortress with unprecedented detail and beauty.",
    "title": "Armok Vision",
    "content_version": "v0.11.2",
    "needs_dfhack": true
    }

Ideally the version and `*_exe` properties would be set by your build scripts, so they would always stay up to date.

**Comment by JapaMala** [comment]
I can generate all of this with the build script. I even have a nice json lib already, that will make it easy.

**Comment by PeridexisErrant** [comment]
Yeah, I thought it would be pretty easy - so many things don't come with a manifest that I have scripts to update them, but as usual it's better to do that upstream if at all possible :smile:

**Comment by JapaMala** [comment]
Fixed by f2a6bd4
