### ISSUE TITLE
Floors/Blocks don't render when looking at them from below

### ISSUE THREAD

**Issue by NahteKavlozs** [JapaMala/armok-vision#39]
When in first person, looking up at floors/blocks causes them to be transparent up to trees. Trees, Stairs, and objects are not affected by this bug.

**Comment by NahteKavlozs** [comment]
![screenshot3](https://cloud.githubusercontent.com/assets/18491562/21754595/427b713c-d5b8-11e6-808d-ac2c2f905757.png)
![screenshot2](https://cloud.githubusercontent.com/assets/18491562/21754596/43305840-d5b8-11e6-8c9c-2ca248ab4c77.png)
![screenshot1](https://cloud.githubusercontent.com/assets/18491562/21754597/43f6e172-d5b8-11e6-8d6a-43b6df9f7745.png)

**Comment by JapaMala** [comment]
Fixed in release 0.16
