### ISSUE TITLE
Armok Vision exits silently on Ubuntu 64

### ISSUE THREAD

**Issue by clickworkorange** [JapaMala/armok-vision#42]
I've got latest Armok Vision (0.15), latest DF (0.43.05) and latest DFHack (0.43.05-beta1 x86_64). DF lauches with DFHack and seems to run very well, but after loading up a fortress and subsequently launching AV it exits silently when I click the "Ok" button: 

```
me@machine:~/ArmokVision$ ./Armok\ Vision.x86_64
Set current directory to /home/me/ArmokVision
Found path: /home/me/ArmokVision/Armok Vision.x86_64
Mono path[0] = '/home/me/ArmokVision/Armok Vision_Data/Managed'
Mono path[1] = '/home/me/ArmokVision/Armok Vision_Data/Mono'
Mono config path = '/home/me/ArmokVision/Armok Vision_Data/Mono/etc'
displaymanager : xrandr version warning. 1.5
displaymanager : trying .X11-unix
client :0 has 1 screens
displaymanager screen (0): 1280 x 800
Using libudev for joystick management


Importing game controller configs
me@machine:~/ArmokVision$ 
```
I haven't been able to find any logfiles or other clues to what the problem might be.

**Comment by JapaMala** [comment]
Hm... I don't currently have a working linux intallation to test, but apparently the log files should be somewhere similar to `~/.config/unity3d/CompanyName/ProductName/Player.log`

**Comment by JapaMala** [comment]
Okay, testing on Kubuntu 64 bit, it runs without issues.

**Comment by JapaMala** [comment]
Nevermind, it causes DF to close with a segfault. Not sure how to debug it.

**Comment by clickworkorange** [comment]
Ok, dusted off an old Windows box and got it running on that. Looks great!

**Comment by lethosor** [comment]
Japa said this appears to be an issue with RemoteFortressReader on Linux. Ordinarily I would reopen this, since the issue still exists, but I'm going to open something in the DFHack repo instead, since that's where RFR is located.
