### ISSUE TITLE
Issue with transferred saved games

### ISSUE THREAD

**Issue by msholly** [JapaMala/armok-vision#56]
Loading up DF 0.43.05 64bit with LNP 0.43.05-r08 and Armok Vision 0.17.0. 

Armok Vision loads up a map perfectly fine with any world generated on my machine. But when I try to load up a recently available world from a YouTuber, I get the following error. 
![df-issue](https://user-images.githubusercontent.com/3991894/32130862-336bbc78-bb55-11e7-8824-d4510de27c9a.jpg)

The Google Analytic issue is probably Pihole, but the TLS issue is only present when loading the downloaded save file. The game run perfectly fine otherwise, so the world works in DF. Its known that the YouTuber does not use DFHack in his series, so that might be a point of failure. 

Let me know if you need any more information from me, and thank you for your work on this!

**Comment by JapaMala** [comment]
It's because you're loading one of Kruggsmash' retired fortress, which, in
the previous version, were not recognized as fort mode. I've since fixed
the issue, but the new AV isn't released yet.

**Comment by msholly** [comment]
It was Kruggsmash! Looking forward to the new release, let me know if I can help as well.

**Comment by JapaMala** [comment]
Fixed in 0.18.0.
