### ISSUE TITLE
Main DF window appears in glitched God Mode, never goes away

### ISSUE THREAD

**Issue by alexchandel** [JapaMala/armok-vision#58]
Occasionally, the game glitches & the main Dwarf Fortress window (i.e. the dwarfort.exe one) is drawn inside Armok Vision as one of the bounds of the area in God Mode.

Moreover, when the game glitches like this, none of the HUD controls work (i.e. attempting to show the minimap, the keyboard help, or the Esc menu all fail), except the toggle between this glitched God Mode & first person mode.

Armok Vision must be restarted.

**Comment by JapaMala** [comment]
The game view is toggled by pressing the ~ key, and when it's open, all other keys are directly piped to Dwarf Fortress.

**Comment by alexchandel** [comment]
Aha, I figured it was some feature I'd accidentally activated.
