### ISSUE TITLE
OS X standalone build broken

### ISSUE THREAD

**Issue by lethosor** [JapaMala/armok-vision#6]
The OS X build of v0.3 displays nothing but a grey screen and "New Text". @kazimuth reports that it only works in the editor on his machine - a newly-built standalone build displays the same problem.

**Comment by kazimuth** [comment]
I added some Debug.logging and the problem went away. I removed the logging and it remained away. I've concluded nothing works or makes sense.
Doing an Assets/Reimport All might help.

**Comment by lethosor** [comment]
v0.4 works for me.
