### ISSUE TITLE
linux_exe in manifest.json needs updated

### ISSUE THREAD

**Issue by carterscottm** [JapaMala/armok-vision#61]
Not a big deal at all, as I can use sed to fix manifest.json in my pack's build script, but thought you should know about it.

**Comment by alexchandel** [comment]
Which file needs to be updated, [this one](https://github.com/JapaMala/armok-vision/blob/master/UnityPackageManager/manifest.json)? What should the change be? Could you post what the new lines should read?

**Comment by carterscottm** [comment]
It's the manifest.json that is packaged with the releases.  I'm not sure if the file is built programmatically or if it's added afterward. The file should look like this:

{
  "author": "Japa, Justin Partain, Kazimuth, Lethosor",
  "content_version": "0.18.0",
  "df_min_version": "0.34.11",
  "df_max_version": "",
  "title": "Armok Vision",
  "tooltip": "A full 3D visualiser - shows off Dwarf Fortress with unprecedented detail and beauty.",
  "win_exe": "Armok Vision.exe",
  "osx_exe": "Armok Vision.app",
  "linux_exe": "Armok Vision Linux.x86_64",
  "launch_with_terminal": false,
  "readme": "Readme.txt",
  "needs_dfhack": true
}

**Comment by JapaMala** [comment]
Fixed in a68954d02c603af1ee91046dc9672a0e63fcdef3
