### ISSUE TITLE
Draw distance of sprites very low

### ISSUE THREAD

**Issue by Dakka21** [JapaMala/armok-vision#62]
Hi, may just be missing a setting here. 

In my current adventure mode playthrough, character sprites only render if they're within about 10 tiles of the camera's position in Armok Vision. I haven't tested in Fortress mode.

The sprites are within vision range of the adventurer. Terrain and such loads in fine. 

I know there's a final option down at the end of the settings toolbar on the left, but it is blocked by the bottom toolbar being in front of it.

Thanks.

**Comment by JapaMala** [comment]
They're set by distance from the Armok Vision camera, and are effected by
the quality settings.

Zooming in will show more people.

**Comment by Dakka21** [comment]
I changed the settings as the very first dialogue box popup from "Performance" to "Fantastic."

The results were fantastic. 

Cheers for the quick response Japa.
