### ISSUE TITLE
Build difficulties on macOS

### ISSUE THREAD

**Issue by alexchandel** [JapaMala/armok-vision#65]
I ran into difficulties attempting to build AV with the README's instructions: `git clone --depth 1 https://github.com/JapaMala/armok-vision.git`, open with Unity 2017.3.1f1 for which the project seems to be configured, and Build.

Immediately after opening, Unity printed the message `Rebuilding Library because the asset database could not be found!`, then printed a few dozen errors of the form `CS0246: The type or namespace name _ could not be found. Are you missing an assembly reference?` for the `AT`, `dfproto`, `IDFStream`, `ColorValue`, and `RemoteFunction` namespaces.

Build attempts print the error `Error building Player because scripts have compile errors in the editor`, and attempting to build Assembly-CSharp directly results in the above namespace errors. What build step am I missing?

**Update:** the README references `Assets/RemoteClientDF`, but this doesn't exist, seemingly having been replaced by the submodule `Assets/RemoteClientDF-Net`. Probably worth mentioning that after step 2 of the README.

Should also mention that the `git clone` will fail unless `git lfs` is installed beforehand.

**Update 2:** the uninitialized git submodule was the original issue. Also worth mentioning in the README that the result of the `git clone --depth 1` is still over 800MB.

**Comment by alexchandel** [comment]
> `You're running version 0.19.0 of the plugin, while Armok Vision expects a plugin versioned 0.19.1 or above.`

There doesn't appear to be a version 0.19.1 of RFR in existence for v0.44.05 (the last Lazy Mac Pack release). Is there any way to build one?

**Comment by alexchandel** [comment]
FWIW here's a macOS build of Armok Vision 85b649c93aaeb27ad42d46eb86e4b661f3eeb883 (post-0.19.1), with the version number changed to 0.19.0 for compatibility with dfhack 0.44.09-r1: [link](https://expirebox.com/download/8bfaf9a8824b56911dfbbee5c289cfad.html). Other than the reported issues, it runs well enough.

**Comment by lethosor** [comment]
Japa forgot to bump the RFR version to 0.19.1 before DFHack 0.44.09-r1 came out. The recommended solution is to ignore the message from AV.

**Comment by alexchandel** [comment]
May've been due to an ever-fluctuating build environment, but I recall getting some null pointer errors when I tried that. It builds now in any case. Hopefully this issue/log will help some poor future soul.

**Comment by alexchandel** [comment]
Ok good to know. Here's a build of Armok Vision's master (79e5ce9b32a01acfb539120cc415a4e34a023c14) with version number 0.19.1 for [64-bit macOS](https://expirebox.com/download/0cfa0d1eba77d006ed6008d13ece0732.html). Feel free to distribute it.

Note that I built it with Unity 2018 (but using MonoDevelop, not the bloated VS for Mac) to work around #67, as in Unity 2018 the fullscreen menu item (but not button) resizes the window to a new desktop while maintaining the original resolution.

I also highly recommend running it with `"targetFrameRate": 30` in the `Config.json` to reduce the latency (#53 and #55).
