### ISSUE TITLE
Up and Down Draw Ranges are ignored at first launch until FPS mode is toggled

### ISSUE THREAD

**Issue by alexchandel** [JapaMala/armok-vision#69]
The initial "Up" and "Down" ranges are completely ignored when AV first launches, until for example FPS mode is toggled.

At first launch (note that the rest of the "Up" and "Down" ranges never load, no matter how long):
<img width="752" alt="screen shot 2018-05-08 at 5 19 47 pm" src="https://user-images.githubusercontent.com/637714/39786048-b37049aa-52ec-11e8-97aa-e65edf392d63.png">

After toggling FPS mode on and off:
<img width="752" alt="screen shot 2018-05-08 at 5 23 02 pm" src="https://user-images.githubusercontent.com/637714/39786075-dd726c06-52ec-11e8-8454-45398f36ca4d.png">

Tested on macOS 10.13.4, AV 0.19.1.

**Comment by JapaMala** [comment]
Fixed in 0.20, I believe. Feel free to re-open if wrong
